import { Banner, Category, Coupon, Order, Product, User } from '../types';

export const INITIAL_USER: User = {
  id: 'usr_78912',
  name: 'Rohit Chouhan',
  phone: '9876543210',
  email: 'rohit@example.com',
  walletBalance: 250,
  addresses: [
    {
      id: 'addr_1',
      tag: 'Home',
      line1: 'Flat 402, Green Valley Apartments',
      line2: 'Sector 62, Near Metro Station',
      city: 'Noida',
      pincode: '201301',
      isDefault: true,
    },
    {
      id: 'addr_2',
      tag: 'Work',
      line1: 'Tower B, 7th Floor, Cyber City',
      line2: 'DLF Phase 2',
      city: 'Gurugram',
      pincode: '122002',
      isDefault: false,
    },
  ],
};

export const MOCK_BANNERS: Banner[] = [
  {
    id: 'ban_1',
    title: '⚡ 10 MINUTE DELIVERY',
    subtitle: 'Get fresh groceries & hot snacks delivered in a blink',
    discount: 'UP TO 50% OFF',
    cta: 'Order Now',
    tag: 'SUPERFAST',
    bgColor: '#0C8346',
    accentColor: '#00FF7F',
    image: 'https://images.unsplash.com/photo-1542838132-92c53300491e?w=800&auto=format&fit=crop&q=60',
  },
  {
    id: 'ban_2',
    title: '🥛 Morning Breakfast Fest',
    subtitle: 'Farm fresh milk, brown eggs, artisanal butter & bread',
    discount: 'FLAT ₹50 OFF',
    cta: 'Explore Dairy',
    tag: 'MORNING SPECIAL',
    bgColor: '#FF9F1C',
    accentColor: '#FFE58F',
    image: 'https://images.unsplash.com/photo-1550583724-b2692b85b150?w=800&auto=format&fit=crop&q=60',
  },
  {
    id: 'ban_3',
    title: '🍟 Late Night Craving Club',
    subtitle: 'Gourmet chips, dips, ice creams & fizzy cold drinks',
    discount: 'BUY 1 GET 1 FREE',
    cta: 'Grab Munchies',
    tag: 'NIGHT EXPRESS',
    bgColor: '#8B5CF6',
    accentColor: '#DDD6FE',
    image: 'https://images.unsplash.com/photo-1566478989037-eec170784d0b?w=800&auto=format&fit=crop&q=60',
  },
  {
    id: 'ban_4',
    title: '🥦 Farm Fresh Organic Harvest',
    subtitle: 'Directly sourced crisp veggies & premium juicy fruits',
    discount: 'EXTRA 20% OFF',
    cta: 'Shop Fresh',
    tag: '100% ORGANIC',
    bgColor: '#059669',
    accentColor: '#A7F3D0',
    image: 'https://images.unsplash.com/photo-1610832958506-aa56368176cf?w=800&auto=format&fit=crop&q=60',
  },
];

export const MOCK_CATEGORIES: Category[] = [
  {
    id: 'cat_fruits_veg',
    name: 'Fruits & Veggies',
    icon: '🥦',
    badge: 'Fresh Farm',
    itemCount: 42,
    image: 'https://images.unsplash.com/photo-1610832958506-aa56368176cf?w=500&auto=format&fit=crop&q=60',
    color: '#E8F8EE',
    accentColor: '#0C8346',
  },
  {
    id: 'cat_dairy_breakfast',
    name: 'Dairy & Bread',
    icon: '🥛',
    badge: 'Morning 7AM',
    itemCount: 38,
    image: 'https://images.unsplash.com/photo-1550583724-b2692b85b150?w=500&auto=format&fit=crop&q=60',
    color: '#FFF4E5',
    accentColor: '#FF9F1C',
  },
  {
    id: 'cat_munchies',
    name: 'Munchies & Chips',
    icon: '🍟',
    badge: 'Party Bites',
    itemCount: 55,
    image: 'https://images.unsplash.com/photo-1566478989037-eec170784d0b?w=500&auto=format&fit=crop&q=60',
    color: '#FEECEC',
    accentColor: '#EF4444',
  },
  {
    id: 'cat_instant_food',
    name: 'Instant Food',
    icon: '🍜',
    badge: '2-Min Craving',
    itemCount: 30,
    image: 'https://images.unsplash.com/photo-1569718212165-3a8278d5f624?w=500&auto=format&fit=crop&q=60',
    color: '#FEF3C7',
    accentColor: '#D97706',
  },
  {
    id: 'cat_cold_drinks',
    name: 'Drinks & Juices',
    icon: '🥤',
    badge: 'Chilled ⚡',
    itemCount: 45,
    image: 'https://images.unsplash.com/photo-1551024709-8f23befc6f87?w=500&auto=format&fit=crop&q=60',
    color: '#E0F2FE',
    accentColor: '#0284C7',
  },
  {
    id: 'cat_sweets_chocolates',
    name: 'Chocolates & Sweets',
    icon: '🍫',
    badge: 'Sweet Tooth',
    itemCount: 34,
    image: 'https://images.unsplash.com/photo-1549007994-cb92caebd54b?w=500&auto=format&fit=crop&q=60',
    color: '#FCE7F3',
    accentColor: '#DB2777',
  },
  {
    id: 'cat_bakery',
    name: 'Bakery & Biscuits',
    icon: '🥐',
    badge: 'Oven Fresh',
    itemCount: 28,
    image: 'https://images.unsplash.com/photo-1509440159596-0249088772ff?w=500&auto=format&fit=crop&q=60',
    color: '#F3E8FF',
    accentColor: '#7C3AED',
  },
  {
    id: 'cat_tea_coffee',
    name: 'Tea & Coffee',
    icon: '☕',
    badge: 'Brew Fresh',
    itemCount: 24,
    image: 'https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?w=500&auto=format&fit=crop&q=60',
    color: '#EDE9FE',
    accentColor: '#6D28D9',
  },
];

export const MOCK_PRODUCTS: Product[] = [
  {
    id: 'prod_1',
    name: 'Amul Taaza Homogenised Toned Milk',
    category: 'cat_dairy_breakfast',
    categoryName: 'Dairy & Bread',
    price: 27,
    mrp: 30,
    discount: 10,
    unit: '500 ml',
    image: 'https://images.unsplash.com/photo-1550583724-b2692b85b150?w=500&auto=format&fit=crop&q=60',
    rating: 4.8,
    ratingCount: 1420,
    isVeg: true,
    etaMinutes: 8,
    bestseller: true,
    description: 'Amul Taaza toned milk is fresh, healthy and nutritious. Pasteurized and homogenized for high quality purity.',
  },
  {
    id: 'prod_2',
    name: 'Amul Salted Butter',
    category: 'cat_dairy_breakfast',
    categoryName: 'Dairy & Bread',
    price: 56,
    mrp: 60,
    discount: 7,
    unit: '100 g',
    image: 'https://images.unsplash.com/photo-1589985270826-4b7bb135bc9d?w=500&auto=format&fit=crop&q=60',
    rating: 4.9,
    ratingCount: 3890,
    isVeg: true,
    etaMinutes: 9,
    bestseller: true,
    description: 'Delicious, creamy salted butter made from purest fresh cream. Perfect for your morning toast and parathas.',
  },
  {
    id: 'prod_3',
    name: 'Harvest Gold 100% Atta Bread',
    category: 'cat_dairy_breakfast',
    categoryName: 'Dairy & Bread',
    price: 50,
    mrp: 55,
    discount: 9,
    unit: '400 g',
    image: 'https://images.unsplash.com/photo-1509440159596-0249088772ff?w=500&auto=format&fit=crop&q=60',
    rating: 4.7,
    ratingCount: 980,
    isVeg: true,
    etaMinutes: 8,
    bestseller: false,
    description: 'Made with 100% whole wheat atta without any added maida. Rich in dietary fiber.',
  },
  {
    id: 'prod_4',
    name: 'Fresh Farm Brown Eggs',
    category: 'cat_dairy_breakfast',
    categoryName: 'Dairy & Bread',
    price: 89,
    mrp: 110,
    discount: 19,
    unit: '6 pcs pack',
    image: 'https://images.unsplash.com/photo-1516467508483-a7212febe31a?w=500&auto=format&fit=crop&q=60',
    rating: 4.8,
    ratingCount: 1250,
    isVeg: false,
    etaMinutes: 10,
    bestseller: true,
    description: 'High protein, antibiotic residue-free farm fresh brown eggs with rich golden yolk.',
  },
  {
    id: 'prod_5',
    name: 'Fresh Hybrid Red Tomato',
    category: 'cat_fruits_veg',
    categoryName: 'Fruits & Veggies',
    price: 28,
    mrp: 40,
    discount: 30,
    unit: '500 g',
    image: 'https://images.unsplash.com/photo-1592924357228-91a4daadcfea?w=500&auto=format&fit=crop&q=60',
    rating: 4.6,
    ratingCount: 2100,
    isVeg: true,
    etaMinutes: 9,
    bestseller: true,
    description: 'Plump, juicy and locally grown red tomatoes. Sourced fresh every morning from local farms.',
  },
  {
    id: 'prod_6',
    name: 'Fresh Green Capsicum (Shimla Mirch)',
    category: 'cat_fruits_veg',
    categoryName: 'Fruits & Veggies',
    price: 35,
    mrp: 50,
    discount: 30,
    unit: '250 g',
    image: 'https://images.unsplash.com/photo-1563565375-f3fdfdbefa83?w=500&auto=format&fit=crop&q=60',
    rating: 4.5,
    ratingCount: 890,
    isVeg: true,
    etaMinutes: 10,
    bestseller: false,
    description: 'Crisp and shiny green capsicums, ideal for stir-fries, pizzas, and curries.',
  },
  {
    id: 'prod_7',
    name: 'Shimla Red Delicious Apple',
    category: 'cat_fruits_veg',
    categoryName: 'Fruits & Veggies',
    price: 149,
    mrp: 199,
    discount: 25,
    unit: '4 pcs (approx 600g)',
    image: 'https://images.unsplash.com/photo-1560806887-1e4cd0b6cbd6?w=500&auto=format&fit=crop&q=60',
    rating: 4.8,
    ratingCount: 780,
    isVeg: true,
    etaMinutes: 11,
    bestseller: true,
    description: 'Sweet and crunchy Shimla apples. Handpicked for maximum crispness and sweetness.',
  },
  {
    id: 'prod_8',
    name: 'Robusta Golden Banana',
    category: 'cat_fruits_veg',
    categoryName: 'Fruits & Veggies',
    price: 45,
    mrp: 60,
    discount: 25,
    unit: '500 g (3-4 pcs)',
    image: 'https://images.unsplash.com/photo-1571771894821-ce9b6c11b08e?w=500&auto=format&fit=crop&q=60',
    rating: 4.7,
    ratingCount: 1640,
    isVeg: true,
    etaMinutes: 8,
    bestseller: false,
    description: 'Naturally ripened, nutrient-packed sweet bananas rich in potassium and energy.',
  },
  {
    id: 'prod_9',
    name: "Lay's India's Magic Masala Chips",
    category: 'cat_munchies',
    categoryName: 'Munchies & Chips',
    price: 20,
    mrp: 20,
    discount: 0,
    unit: '48 g',
    image: 'https://images.unsplash.com/photo-1566478989037-eec170784d0b?w=500&auto=format&fit=crop&q=60',
    rating: 4.9,
    ratingCount: 5420,
    isVeg: true,
    etaMinutes: 7,
    bestseller: true,
    description: "Crunchy ridge-cut potato chips with bold, iconic Indian spices. Everyone's favorite munchie.",
  },
  {
    id: 'prod_10',
    name: 'Doritos Cheese Nacho Chips',
    category: 'cat_munchies',
    categoryName: 'Munchies & Chips',
    price: 50,
    mrp: 55,
    discount: 9,
    unit: '90 g',
    image: 'https://images.unsplash.com/photo-1513456852971-30c0b8199d4d?w=500&auto=format&fit=crop&q=60',
    rating: 4.8,
    ratingCount: 2340,
    isVeg: true,
    etaMinutes: 8,
    bestseller: true,
    description: 'Intense cheesy burst with maximum crunch in every triangle bite.',
  },
  {
    id: 'prod_11',
    name: 'Act II Golden Sizzle Butter Popcorn',
    category: 'cat_munchies',
    categoryName: 'Munchies & Chips',
    price: 35,
    mrp: 40,
    discount: 12,
    unit: '70 g',
    image: 'https://images.unsplash.com/photo-1585647347483-22b66260dfff?w=500&auto=format&fit=crop&q=60',
    rating: 4.6,
    ratingCount: 1120,
    isVeg: true,
    etaMinutes: 8,
    bestseller: false,
    description: 'Hot and fresh microwaveable popcorn with a rich buttery coating for movie nights.',
  },
  {
    id: 'prod_12',
    name: 'Maggi 2-Minute Instant Masala Noodles',
    category: 'cat_instant_food',
    categoryName: 'Instant Food',
    price: 58,
    mrp: 60,
    discount: 3,
    unit: 'Pack of 4 (280g)',
    image: 'https://images.unsplash.com/photo-1569718212165-3a8278d5f624?w=500&auto=format&fit=crop&q=60',
    rating: 4.9,
    ratingCount: 7800,
    isVeg: true,
    etaMinutes: 7,
    bestseller: true,
    description: "India's beloved 2-minute snack. Signature blend of 10 roasted spices in every bite.",
  },
  {
    id: 'prod_13',
    name: 'Samyang Buldak 2x Spicy Hot Chicken Ramen',
    category: 'cat_instant_food',
    categoryName: 'Instant Food',
    price: 135,
    mrp: 160,
    discount: 16,
    unit: '140 g',
    image: 'https://images.unsplash.com/photo-1612927601601-6638404737ce?w=500&auto=format&fit=crop&q=60',
    rating: 4.7,
    ratingCount: 3410,
    isVeg: false,
    etaMinutes: 10,
    bestseller: true,
    description: 'Ultra spicy Korean stir-fried ramen. Extremely hot, flavorful and dangerously addictive!',
  },
  {
    id: 'prod_14',
    name: 'Coca-Cola Original Chilled Soft Drink',
    category: 'cat_cold_drinks',
    categoryName: 'Drinks & Juices',
    price: 40,
    mrp: 40,
    discount: 0,
    unit: '750 ml Bottle',
    image: 'https://images.unsplash.com/photo-1554866585-cd94860890b7?w=500&auto=format&fit=crop&q=60',
    rating: 4.9,
    ratingCount: 4210,
    isVeg: true,
    etaMinutes: 8,
    bestseller: true,
    description: 'Crisp, refreshing and effervescent. Delivered ice-chilled to beat the heat instantly.',
  },
  {
    id: 'prod_15',
    name: 'Real Activ 100% Mixed Fruit Juice',
    category: 'cat_cold_drinks',
    categoryName: 'Drinks & Juices',
    price: 125,
    mrp: 140,
    discount: 11,
    unit: '1 L Tetra',
    image: 'https://images.unsplash.com/photo-1621506289937-a8e4df240d0b?w=500&auto=format&fit=crop&q=60',
    rating: 4.7,
    ratingCount: 1820,
    isVeg: true,
    etaMinutes: 9,
    bestseller: false,
    description: 'No added sugar, no added preservatives. 100% fruit juice packed with natural vitamins.',
  },
  {
    id: 'prod_16',
    name: 'Cadbury Dairy Milk Silk Bar',
    category: 'cat_sweets_chocolates',
    categoryName: 'Chocolates & Sweets',
    price: 85,
    mrp: 90,
    discount: 6,
    unit: '60 g',
    image: 'https://images.unsplash.com/photo-1549007994-cb92caebd54b?w=500&auto=format&fit=crop&q=60',
    rating: 4.9,
    ratingCount: 6120,
    isVeg: true,
    etaMinutes: 8,
    bestseller: true,
    description: 'Unbelievably smooth, rich and creamy milk chocolate that simply melts in your mouth.',
  },
  {
    id: 'prod_17',
    name: 'Ferrero Rocher Hazelnut Chocolates Box',
    category: 'cat_sweets_chocolates',
    categoryName: 'Chocolates & Sweets',
    price: 495,
    mrp: 549,
    discount: 10,
    unit: '16 Pcs (200g)',
    image: 'https://images.unsplash.com/photo-1582293041079-7814c2f12063?w=500&auto=format&fit=crop&q=60',
    rating: 4.9,
    ratingCount: 2100,
    isVeg: true,
    etaMinutes: 10,
    bestseller: true,
    description: 'Crispy hazelnut wafer sphere covered in milk chocolate and finely chopped hazelnuts.',
  },
  {
    id: 'prod_18',
    name: 'Oreo Original Vanilla Creme Cookies',
    category: 'cat_bakery',
    categoryName: 'Bakery & Biscuits',
    price: 35,
    mrp: 40,
    discount: 12,
    unit: '120 g',
    image: 'https://images.unsplash.com/photo-1558961363-fa8fdf82db35?w=500&auto=format&fit=crop&q=60',
    rating: 4.8,
    ratingCount: 3540,
    isVeg: true,
    etaMinutes: 8,
    bestseller: true,
    description: 'Rich chocolate biscuit sandwich with signature sweet vanilla cream filling. Twist, lick, dunk!',
  },
  {
    id: 'prod_19',
    name: 'Nescafe Classic Instant Coffee Jar',
    category: 'cat_tea_coffee',
    categoryName: 'Tea & Coffee',
    price: 185,
    mrp: 210,
    discount: 12,
    unit: '50 g Glass Jar',
    image: 'https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?w=500&auto=format&fit=crop&q=60',
    rating: 4.8,
    ratingCount: 4290,
    isVeg: true,
    etaMinutes: 9,
    bestseller: true,
    description: '100% pure natural coffee beans roasted to perfection for an invigorating morning aroma.',
  },
  {
    id: 'prod_20',
    name: 'Tata Tea Gold Leaf Premium Tea',
    category: 'cat_tea_coffee',
    categoryName: 'Tea & Coffee',
    price: 275,
    mrp: 310,
    discount: 11,
    unit: '500 g Pack',
    image: 'https://images.unsplash.com/photo-1576092768241-dec231879fc3?w=500&auto=format&fit=crop&q=60',
    rating: 4.7,
    ratingCount: 2780,
    isVeg: true,
    etaMinutes: 9,
    bestseller: false,
    description: 'Exquisite blend of rich Assam CTC teas with gently rolled long leaves for rich taste and aroma.',
  },
];

export const MOCK_COUPONS: Coupon[] = [
  {
    code: 'ZAP100',
    title: 'Flat ₹100 Instant Discount',
    description: 'Valid on orders above ₹299',
    discountAmount: 100,
    minOrderValue: 299,
    type: 'flat',
  },
  {
    code: 'FREESHIP',
    title: 'Free Delivery',
    description: 'Zero delivery charges on your order',
    discountAmount: 25,
    minOrderValue: 149,
    type: 'free_delivery',
  },
  {
    code: 'WELCOME50',
    title: '₹50 Off for New Users',
    description: 'Get ₹50 off on first 3 orders',
    discountAmount: 50,
    minOrderValue: 199,
    type: 'flat',
  },
  {
    code: 'CRAVING20',
    title: '20% Mega Cashback',
    description: 'Up to ₹80 discount on munchies',
    discountPercent: 20,
    maxDiscount: 80,
    minOrderValue: 199,
    type: 'percent',
  },
];

export const INITIAL_ORDERS: Order[] = [
  {
    id: 'ZB-4829-M',
    createdAt: new Date(Date.now() - 3600000 * 3).toISOString(),
    status: 'DELIVERED',
    deliveryEtaMinutes: 0,
    items: [
      {
        id: 'prod_1',
        name: 'Amul Taaza Homogenised Toned Milk',
        price: 27,
        quantity: 2,
        unit: '500 ml',
        image: 'https://images.unsplash.com/photo-1550583724-b2692b85b150?w=500&auto=format&fit=crop&q=60',
      },
      {
        id: 'prod_3',
        name: 'Harvest Gold 100% Atta Bread',
        price: 50,
        quantity: 1,
        unit: '400 g',
        image: 'https://images.unsplash.com/photo-1509440159596-0249088772ff?w=500&auto=format&fit=crop&q=60',
      },
    ],
    bill: {
      itemTotal: 104,
      deliveryFee: 0,
      handlingFee: 4,
      tip: 10,
      discount: 0,
      grandTotal: 118,
      savingsTotal: 11,
    },
    paymentMethod: 'UPI (PhonePe)',
    paymentStatus: 'PAID',
    deliveryAddress: {
      id: 'addr_1',
      tag: 'Home',
      line1: 'Flat 402, Green Valley Apartments',
      city: 'Noida',
      pincode: '201301',
    },
    deliveryInstructions: ['Leave at door'],
    deliveryPartner: {
      name: 'Rahul Sharma',
      phone: '+91 98765 43210',
      vehicle: 'Honda Activa (UP 16 AB 4590)',
      rating: 4.9,
      deliveriesCount: 1420,
    },
  },
];
